---
- name: Copy flume bin
  synchronize: mode=pull src=/publish/flume dest=/usr/local

- name: add java_home
  script: /usr/local/flume/apache-flume-1.4.0-bin/conf/flume-env.sh

- name: config flume
  template: src=server.conf dest=/usr/local/flume/apache-flume-1.4.0-bin/conf/server.conf

- name: start flume-ng
  command: chdir=/usr/local/flume/apache-flume-1.4.0-bin sh -c "/usr/bin/nohup /usr/local/flume/apache-flume-1.4.0-bin/bin/flume-ng agent -c conf -f conf/server.conf -n agent -Dflume.root.logger=INFO,console >> /data1/logs/flume/server.log 2>&1 &"
